version: '2'

services:
  db:
    restart: always
    image: postgres:latest
    ports:
      - "5000:5432"
    volumes:
      - ./src/main/resources/db/init_db_data.sql:/docker-entrypoint-initdb.d/init.sql

  data-service:
    restart: always
    image: tomassukenik/react-app:hateoas-service-0.0.1
    ports:
      - "9000:8081"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=
#    env_file:
#      - .env
