version: '2'

services:
  db:
    restart: always
    image: postgres:12.3
    ports:
      - "5000:5432"
    volumes:
      - ./src/main/resources/db/init_db_data.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres

  rabbitmq:
    image: rabbitmq:3.8.3-management
    ports:
      - "5672:5672"
      - "15672:15672"

