server:
  port : 8081

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${MSG_BROKER_HOST}

broker:
  queue:
    name: ${MSG_QUEUE_NAME}
